export {default as Navbar} from "./Navbar"
export {default as Hero} from "./Hero"
export {default as Card} from "./Card"
export {default as About} from "./About"
export {default as Banner} from "./Banner"
export {default as Footer} from "./Footer"